# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #
# User Settings
# This is where you put your own settings as this will not be touched during update 
# if the upgrade.sh is used.

# refer to Hyprland wiki for more info https://wiki.hyprland.org/Configuring/Variables/

# NOTE: some settings are in ~/.config/hypr/UserConfigs/UserDecorAnimations.conf

dwindle {
  pseudotile = yes
  preserve_split = yes
  force_split = 0
  smart_resizing = false 
}
xwayland {
  force_zero_scaling = true
}
master {
  new_status = slave 
  new_on_top = true
  mfact = 0.38
  slave_count_for_center_master = 0
  orientation = center
  allow_small_split = true
  # inherit_fullscreen = false 
  always_keep_position = true
}

general {
    # See https://wiki.hyprland.org/Configuring/Variables/ for more

    gaps_in = 6
    gaps_out = 2
    border_size = 5
    col.active_border = rgba(33ccffee) rgba(00ff99ee) 45deg
    col.inactive_border = rgba(595959aa)
    layout = master 
    resize_on_border = true
}

input {
  kb_layout = us
  kb_variant =
  kb_model =
  kb_options =
  kb_rules =
  repeat_rate = 50
  repeat_delay = 300
  scroll_factor = 0.6	
  scroll_method = 2fg
  sensitivity = 1.6 #mouse sensitivity
  # scroll_button_lock = true
  # new_window_takes_over_fullscreen = true
  #accel_profile =     # flat or adaptive or blank or EMPTY means libinput’s default mode
  numlock_by_default = false
  left_handed = false
  follow_mouse = true
  float_switch_override_focus = false

  touchpad {
    disable_while_typing = true
    natural_scroll = true 
    clickfinger_behavior = false
    middle_button_emulation = true
    tap-to-click = true
    drag_lock = false
          }
  
  # below for devices with touchdevice ie. touchscreen
	touchdevice {
		enabled = false
	}
	
	# below is for table see link above for proper variables
	tablet {
		transform = 0
		left_handed = 0
	}
}

# gestures {
#   workspace_swipe = false
#   workspace_swipe_fingers = 3
#   workspace_swipe_distance = 500
#   workspace_swipe_invert = true
#   workspace_swipe_min_speed_to_force = 30
#   workspace_swipe_cancel_ratio = 0.5
#   workspace_swipe_create_new = true 
#   workspace_swipe_forever = true
#   #workspace_swipe_use_r = true #uncomment if wanted a forever create a new workspace with swipe right
# }

misc {
  disable_hyprland_logo = true
  disable_splash_rendering = true
  vfr = true
  vrr = 2
  mouse_move_enables_dpms = true
  enable_swallow = off
  swallow_regex = ^(kitty)$
  focus_on_activate = false
  initial_workspace_tracking = 0
  middle_click_paste = true
}

opengl {
  nvidia_anti_flicker = true
}

binds {
  workspace_back_and_forth = true
  allow_workspace_cycles = true
  pass_mouse_when_bound = false
}

#Could help when scaling and not pixelating
xwayland {
  enabled = true
  force_zero_scaling = true
}

render {
  # explicit_sync = 2
  # explicit_sync_kms = 2
  direct_scanout = 0
}

cursor {
  sync_gsettings_theme = true
  no_hardware_cursors =  1 # change to 1 if want to disable
  enable_hyprcursor = true
  warp_on_change_workspace = 2
  no_warps = true 
}
